/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  sym_label = 2,
  sym_remark = 3,
  sym_command = 4,
  sym_variable_numeric = 5,
  sym_variable_string = 6,
  sym_rand_call = 7,
  anon_sym_EQ_EQ = 8,
  anon_sym_BANG_EQ = 9,
  anon_sym_GT_EQ = 10,
  anon_sym_LT_EQ = 11,
  anon_sym_GT = 12,
  anon_sym_LT = 13,
  sym_operator_char = 14,
  sym_text_fragment = 15,
  sym_source_file = 16,
  sym_statement = 17,
  sym_body = 18,
  sym_operator = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_body_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [sym_label] = "label",
  [sym_remark] = "remark",
  [sym_command] = "command",
  [sym_variable_numeric] = "variable_numeric",
  [sym_variable_string] = "variable_string",
  [sym_rand_call] = "rand_call",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [sym_operator_char] = "operator_char",
  [sym_text_fragment] = "text_fragment",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_body] = "body",
  [sym_operator] = "operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [sym_label] = sym_label,
  [sym_remark] = sym_remark,
  [sym_command] = sym_command,
  [sym_variable_numeric] = sym_variable_numeric,
  [sym_variable_string] = sym_variable_string,
  [sym_rand_call] = sym_rand_call,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [sym_operator_char] = sym_operator_char,
  [sym_text_fragment] = sym_text_fragment,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_body] = sym_body,
  [sym_operator] = sym_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_remark] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_numeric] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_string] = {
    .visible = true,
    .named = true,
  },
  [sym_rand_call] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_operator_char] = {
    .visible = true,
    .named = true,
  },
  [sym_text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 4,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static const TSCharacterRange sym_command_character_set_1[] = {
  {'A', 'A'}, {'C', 'C'}, {'E', 'E'}, {'J', 'J'}, {'M', 'M'}, {'S', 'U'}, {'a', 'a'}, {'c', 'c'},
  {'e', 'e'}, {'j', 'j'}, {'m', 'm'}, {'s', 'u'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '\n', 16,
        '\r', 1,
        '!', 30,
        '#', 10,
        '$', 11,
        '*', 12,
        '<', 29,
        '=', 31,
        '>', 28,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(5);
      if (set_contains(sym_command_character_set_1, 12, lookahead)) ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        ':', 18,
        '\t', 4,
        ' ', 4,
        'A', 9,
        'a', 9,
        'N', 4,
        'Y', 4,
        'n', 4,
        'y', 4,
      );
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == 'N' ||
          lookahead == 'Y' ||
          lookahead == 'n' ||
          lookahead == 'y') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(2);
      END_STATE();
    case 9:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 10:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 11:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 12:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ')') ADVANCE(3);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '\n', 16,
        '\r', 32,
        '!', 30,
        '#', 10,
        '$', 11,
        '<', 29,
        '=', 31,
        '>', 28,
        '\t', 33,
        ' ', 33,
        'R', 37,
        'r', 37,
      );
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_label);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_remark);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_command);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_variable_numeric);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_variable_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_rand_call);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_rand_call);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_operator_char);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_operator_char);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == '!' ||
          lookahead == '#' ||
          lookahead == '$' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '!' ||
          lookahead == '#' ||
          lookahead == '$' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text_fragment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_remark] = ACTIONS(1),
    [sym_command] = ACTIONS(1),
    [sym_variable_numeric] = ACTIONS(1),
    [sym_variable_string] = ACTIONS(1),
    [sym_rand_call] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [sym_operator_char] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(16),
    [sym_statement] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_source_file_token1] = ACTIONS(5),
    [sym_label] = ACTIONS(7),
    [sym_remark] = ACTIONS(7),
    [sym_command] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_body] = STATE(14),
    [sym_operator] = STATE(3),
    [aux_sym_body_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [aux_sym_source_file_token1] = ACTIONS(13),
    [sym_variable_numeric] = ACTIONS(15),
    [sym_variable_string] = ACTIONS(15),
    [sym_rand_call] = ACTIONS(15),
    [anon_sym_EQ_EQ] = ACTIONS(17),
    [anon_sym_BANG_EQ] = ACTIONS(17),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(17),
    [sym_operator_char] = ACTIONS(15),
    [sym_text_fragment] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_operator] = STATE(4),
    [aux_sym_body_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [aux_sym_source_file_token1] = ACTIONS(21),
    [sym_variable_numeric] = ACTIONS(23),
    [sym_variable_string] = ACTIONS(23),
    [sym_rand_call] = ACTIONS(23),
    [anon_sym_EQ_EQ] = ACTIONS(17),
    [anon_sym_BANG_EQ] = ACTIONS(17),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(17),
    [sym_operator_char] = ACTIONS(23),
    [sym_text_fragment] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym_operator] = STATE(4),
    [aux_sym_body_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(25),
    [aux_sym_source_file_token1] = ACTIONS(27),
    [sym_variable_numeric] = ACTIONS(29),
    [sym_variable_string] = ACTIONS(29),
    [sym_rand_call] = ACTIONS(29),
    [anon_sym_EQ_EQ] = ACTIONS(32),
    [anon_sym_BANG_EQ] = ACTIONS(32),
    [anon_sym_GT_EQ] = ACTIONS(32),
    [anon_sym_LT_EQ] = ACTIONS(32),
    [anon_sym_GT] = ACTIONS(32),
    [anon_sym_LT] = ACTIONS(32),
    [sym_operator_char] = ACTIONS(29),
    [sym_text_fragment] = ACTIONS(29),
  },
  [STATE(5)] = {
    [sym_body] = STATE(14),
    [sym_operator] = STATE(6),
    [aux_sym_body_repeat1] = STATE(6),
    [aux_sym_source_file_token1] = ACTIONS(13),
    [sym_variable_numeric] = ACTIONS(35),
    [sym_variable_string] = ACTIONS(35),
    [sym_rand_call] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(37),
    [anon_sym_BANG_EQ] = ACTIONS(37),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(37),
    [sym_operator_char] = ACTIONS(35),
    [sym_text_fragment] = ACTIONS(35),
  },
  [STATE(6)] = {
    [sym_operator] = STATE(7),
    [aux_sym_body_repeat1] = STATE(7),
    [aux_sym_source_file_token1] = ACTIONS(21),
    [sym_variable_numeric] = ACTIONS(39),
    [sym_variable_string] = ACTIONS(39),
    [sym_rand_call] = ACTIONS(39),
    [anon_sym_EQ_EQ] = ACTIONS(37),
    [anon_sym_BANG_EQ] = ACTIONS(37),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(37),
    [sym_operator_char] = ACTIONS(39),
    [sym_text_fragment] = ACTIONS(39),
  },
  [STATE(7)] = {
    [sym_operator] = STATE(7),
    [aux_sym_body_repeat1] = STATE(7),
    [aux_sym_source_file_token1] = ACTIONS(27),
    [sym_variable_numeric] = ACTIONS(41),
    [sym_variable_string] = ACTIONS(41),
    [sym_rand_call] = ACTIONS(41),
    [anon_sym_EQ_EQ] = ACTIONS(44),
    [anon_sym_BANG_EQ] = ACTIONS(44),
    [anon_sym_GT_EQ] = ACTIONS(44),
    [anon_sym_LT_EQ] = ACTIONS(44),
    [anon_sym_GT] = ACTIONS(44),
    [anon_sym_LT] = ACTIONS(44),
    [sym_operator_char] = ACTIONS(41),
    [sym_text_fragment] = ACTIONS(41),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(47),
    [aux_sym_source_file_token1] = ACTIONS(49),
    [sym_variable_numeric] = ACTIONS(49),
    [sym_variable_string] = ACTIONS(49),
    [sym_rand_call] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_BANG_EQ] = ACTIONS(49),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(49),
    [sym_operator_char] = ACTIONS(49),
    [sym_text_fragment] = ACTIONS(49),
  },
  [STATE(9)] = {
    [aux_sym_source_file_token1] = ACTIONS(49),
    [sym_variable_numeric] = ACTIONS(49),
    [sym_variable_string] = ACTIONS(49),
    [sym_rand_call] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_BANG_EQ] = ACTIONS(49),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(49),
    [sym_operator_char] = ACTIONS(49),
    [sym_text_fragment] = ACTIONS(49),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      sym_command,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      aux_sym_source_file_token1,
    STATE(11), 1,
      aux_sym_source_file_repeat1,
    STATE(15), 1,
      sym_statement,
    ACTIONS(55), 2,
      sym_label,
      sym_remark,
  [20] = 6,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      aux_sym_source_file_token1,
    ACTIONS(65), 1,
      sym_command,
    STATE(11), 1,
      aux_sym_source_file_repeat1,
    STATE(17), 1,
      sym_statement,
    ACTIONS(62), 2,
      sym_label,
      sym_remark,
  [40] = 1,
    ACTIONS(57), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      sym_label,
      sym_remark,
      sym_command,
  [48] = 2,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      aux_sym_source_file_token1,
  [55] = 1,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
  [60] = 2,
    ACTIONS(68), 1,
      aux_sym_source_file_token1,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
  [67] = 1,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
  [71] = 1,
    ACTIONS(68), 1,
      aux_sym_source_file_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 20,
  [SMALL_STATE(12)] = 40,
  [SMALL_STATE(13)] = 48,
  [SMALL_STATE(14)] = 55,
  [SMALL_STATE(15)] = 60,
  [SMALL_STATE(16)] = 67,
  [SMALL_STATE(17)] = 71,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pilot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
